### ISSUE TITLE
how to use in native php

### ISSUE THREAD

**Issue by satriani04** [philsturgeon/codeigniter-restclient#49]
i tried to develop api with https://github.com/chriskacerguis/codeigniter-restserver and it's work fine to me.

i have a client with native php.
how to use this repo in native php.

thanks

**Comment by chriskacerguis** [comment]
What do you mean by "native php"

**Comment by satriani04** [comment]
php with no framework...

**Comment by chriskacerguis** [comment]
Ahh.  Thanks for clarifying.  There really is no easy way, as we use a lot of the code igniter framework.

**Comment by satriani04** [comment]
do you have any idea how to use in native php? cause my client use only native php
